from typing import TypedDict, Annotated
import asyncio
import operator

from langchain_core.messages import BaseMessage, HumanMessage, SystemMessage
from langchain_core.tools import tool
from langgraph.graph import StateGraph, END
from langgraph.prebuilt import create_react_agent

from src.llm import llm
from src.rag import build_vectorstore, get_retriever, load_documents, chunk_documents
from src.agent import calculator, doc_search


class GraphState(TypedDict):
    messages: Annotated[list[BaseMessage], operator.add]
    retrieved_context: str


# -------------------------------------------------------------------
# Load documents and build/connect to vector store
# -------------------------------------------------------------------

_documents = load_documents()
_chunks = chunk_documents(_documents)

_vectorstore = build_vectorstore(
    _chunks,
    recreate=False,
)

_retriever = get_retriever(
    _vectorstore,
    k=3,
)


# -------------------------------------------------------------------
# Retrieval tool
# -------------------------------------------------------------------

@tool
async def retrieve_papers(query: str) -> str:
    """Search the speaker-embedding papers for relevant context."""

    docs = await _retriever.ainvoke(query)

    if not docs:
        return "No relevant content found in the source papers."

    return "\n\n".join(
        f"[{doc.metadata.get('source', 'unknown')} "
        f"p.{doc.metadata.get('page', 'unknown')}] "
        f"{doc.page_content}"
        for doc in docs
    )


# -------------------------------------------------------------------
# Agent
# -------------------------------------------------------------------

tools = [
    calculator,
    doc_search,
    retrieve_papers,
]

agent_executor = create_react_agent(
    llm,
    tools,
)


# -------------------------------------------------------------------
# Retrieve node
# -------------------------------------------------------------------

async def retrieve_node(state: GraphState) -> GraphState:
    """Retrieve relevant document chunks for the user's query."""

    last_message = state["messages"][-1]

    query = last_message.content

    docs = await _retriever.ainvoke(query)

    context = "\n\n".join(
        doc.page_content
        for doc in docs
    )

    return {
        "messages": [],
        "retrieved_context": context,
    }


# -------------------------------------------------------------------
# Agent node
# -------------------------------------------------------------------

async def agent_node(state: GraphState) -> GraphState:
    """Run the ReAct agent using the retrieved document context."""

    context = state.get(
        "retrieved_context",
        "",
    )

    grounding = SystemMessage(
        content=(
            "Use the following retrieved context from the source papers "
            "to answer the user's question. "
            "If the context does not contain the answer, "
            "say so rather than relying on outside knowledge.\n\n"
            f"Context:\n{context}"
        ),
    )

    input_messages = [
        grounding,
        *state["messages"],
    ]

    result = await agent_executor.ainvoke(
        {
            "messages": input_messages,
        }
    )

    # Keep only messages generated by the agent.
    new_messages = result["messages"][len(input_messages):]

    return {
        "messages": new_messages,
        "retrieved_context": context,
    }


# -------------------------------------------------------------------
# Generate node
# -------------------------------------------------------------------

async def generate_node(state: GraphState) -> GraphState:
    """
    Final generation stage.

    The agent currently performs the actual generation,
    so this node simply passes the state forward.
    """

    return state


# -------------------------------------------------------------------
# Build LangGraph workflow
# -------------------------------------------------------------------

workflow = StateGraph(GraphState)

workflow.add_node(
    "retrieve",
    retrieve_node,
)

workflow.add_node(
    "agent",
    agent_node,
)

workflow.add_node(
    "generate",
    generate_node,
)

workflow.set_entry_point("retrieve")

workflow.add_edge(
    "retrieve",
    "agent",
)

workflow.add_edge(
    "agent",
    "generate",
)

workflow.add_edge(
    "generate",
    END,
)

graph = workflow.compile()


# -------------------------------------------------------------------
# Async test
# -------------------------------------------------------------------

async def test_async_graph():
    """Run a simple asynchronous test of the graph."""

    result = await graph.ainvoke(
        {
            "messages": [
                HumanMessage(
                    content=(
                        "What is statistics pooling "
                        "in the x-vector system?"
                    )
                )
            ],
            "retrieved_context": "",
        }
    )

    print("\n--- Async Graph Result ---")

    for message in result["messages"]:
        print(
            f"[{message.type}] {message.content}"
        )


# -------------------------------------------------------------------
# Main
# -------------------------------------------------------------------

if __name__ == "__main__":

    # Generate architecture diagram
    graph.get_graph().draw_mermaid_png(
        output_file_path="docs/architecture_diagram.png"
    )

    print(
        "Saved architecture diagram to "
        "docs/architecture_diagram.png"
    )

    # Run async graph test
    asyncio.run(
        test_async_graph()
    )